name: cat_calories
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  math_expressions: ^2.6.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  file: ^7.0.1

flutter:
  uses-material-design: true

  assets:
    - images/cats/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600